### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by jeffallen**
Fixed package name confusion.

### CODE REVIEW

**Comment by jeffallen** [comment]
Nevermind. But that's just whack that the repo name and the package name are not the same. Way confusing.

**Comment by tarm** [comment]
I agree with you, but it would break people's code to change the package name or import path now.

This repo (and naming) predate the go tool as you can tell from the README.

I am considering making a new package github.com/tarm/serial that would fix the import path issue and also allow a few backwards-incompatible changes (since the import path would then be different it wouldn't break people's code).

**Comment by tarm** [comment]
OK, I just renamed the package, made a backwards incompatible change, and then restore goserial for backwards compatibility.

The new package path is github.com/tarm/serial

**Comment by jeffallen** [comment]
Thx. Two thumbs up!

**Pull request closed without merging**
